#!/bin/bash -l
#PBS -N matlab_job
#PBS -A UWAS0094
#PBS -l select=1:ncpus=1:mem=16GB
#PBS -l walltime=24:00:00
#PBS -q casper
#PBS -j oe

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR
module load matlab

### Run program
matlab -batch script_cmip5
matlab -batch script_cmip6
